# Configuration file for HarderWardens plugin
# You can set Warden's difficulty level here

# WARDEN'S DIFFICULTY LEVEL
# This will apply to all Wardens (except the warden's name)
# (Default = NORMAL; More difficulty details below)
warden_difficulty: EASY

# Difficulties: EASY, NORMAL, HARD (more difficulties are planned for future updates!)

# Difficulty EASY details:
#   Warden's Health: 60 hp (30 hearts)
#   Warden's Damage: 0.1x multiplier

# Difficulty NORMAL details:
#   Warden's Health: 500 hp (250 hearts)
#   Warden's Damage: 2.2x multiplier

# Difficulty HARD details:
#   Warden's Health: 1000 hp (500 hearts)
#   Warden's Damage: 3.5x multiplier

# Last updated for HarderWardens v1.1.3
# Version 1.1.3 works for MC versions 1.21 - 1.21.7
# End of config file
